#!/usr/bin/env python3
"""Concatenates src/*.js (ES modules) into one classic script, game.bundle.js, so the game
works when index.html is opened directly via file:// (double-click) -- ES modules are blocked
by CORS under file://, which was a real bug users hit. Run this after editing anything in src/.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"

# Dependency order matters for classic scripts (no hoisting across files at parse time in a
# way that matters here since everything runs top-to-bottom, but keep it topological anyway).
ORDER = [
    "core.js", "assets.js", "traits.js", "backstories.js", "grid.js", "zones.js", "economy.js", "research.js", "resources.js", "vehicles.js",
    "rooms.js", "ranks.js", "power.js", "water.js", "augments.js", "citizens.js", "coverageplans.js", "security.js", "siege.js", "relationships.js", "director.js",
    "schedule.js", "sickness.js", "epidemic.js", "supplies.js", "programs.js", "jobs.js", "drones.js", "forcejob.js", "draft.js", "factions.js", "worldmap.js", "fire.js", "weather.js", "rats.js", "anomaly.js", "grading.js", "audio.js", "metaprogress.js", "grants.js", "world.js", "render.js", "input.js", "tutorial.js", "main.js",
]

IMPORT_RE = re.compile(r"^\s*import\s+[\s\S]*?from\s+['\"][^'\"]*['\"];?\s*$", re.MULTILINE)
EXPORT_RE = re.compile(r"^export\s+", re.MULTILINE)
# `import * as foo from './bar.js'` -- the plain IMPORT_RE strip above just deletes the line, which
# works fine for named imports (the bundled `const`/`function`/`class` declarations from bar.js are
# already in global scope by the time foo.js's code runs) but leaves a dangling `foo.` reference for
# namespace imports since there's no `foo` object anywhere in a flattened classic script. Detect
# those and synthesize `const foo = { name1, name2, ... };` from bar.js's own export names so the
# namespace-style call sites (e.g. audio.playKill()) keep working.
NAMESPACE_IMPORT_RE = re.compile(r"^\s*import\s+\*\s+as\s+(\w+)\s+from\s+['\"]\./(\w+)\.js['\"];?\s*$", re.MULTILINE)
EXPORT_NAME_RE = re.compile(r"^export\s+(?:async\s+function|function|class|const|let|var)\s+([A-Za-z0-9_]+)", re.MULTILINE)

def main():
    parts = ["// AUTO-GENERATED by build.py -- do not edit directly, edit src/*.js and rerun.\n"]
    seen_aliases = set()
    for name in ORDER:
        raw = (SRC / name).read_text(encoding="utf-8")
        text = IMPORT_RE.sub("", raw)
        text = EXPORT_RE.sub("", text)
        parts.append(f"\n// ---- {name} ----\n{text}")
        # Emit any namespace-import alias this file needs right after its own section -- by this
        # point in the bundle the imported module's own `const`/`function` declarations already
        # exist (it precedes `name` in ORDER), so `const foo = { ... }` here is safe, whereas
        # deferring all aliases to the end of the bundle would throw a TDZ ReferenceError for any
        # code in `name` that runs at top-level (not inside a later callback).
        for alias, module in NAMESPACE_IMPORT_RE.findall(raw):
            if alias in seen_aliases:
                continue
            seen_aliases.add(alias)
            module_file = SRC / f"{module}.js"
            if module_file.exists():
                export_names = EXPORT_NAME_RE.findall(module_file.read_text(encoding="utf-8"))
                parts.append(f"const {alias} = {{ {', '.join(export_names)} }}; // namespace-import alias for {module}.js")
    bundle = "\n".join(parts)
    (ROOT / "game.bundle.js").write_text(bundle, encoding="utf-8")
    print(f"wrote game.bundle.js ({len(bundle)} bytes)")

if __name__ == "__main__":
    main()
