#!/usr/bin/env python3
"""Concatenates src/*.js (ES modules) into one classic script, game.bundle.js, so the game
works when index.html is opened directly via file:// (double-click) -- ES modules are blocked
by CORS under file://, which was a real bug users hit. Run this after editing anything in src/.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"

# Dependency order matters for classic scripts (no hoisting across files at parse time in a
# way that matters here since everything runs top-to-bottom, but keep it topological anyway).
ORDER = [
    "core.js", "traits.js", "grid.js", "zones.js", "economy.js", "resources.js", "vehicles.js",
    "citizens.js", "security.js", "siege.js", "relationships.js", "director.js",
    "jobs.js", "world.js", "render.js", "input.js", "main.js",
]

IMPORT_RE = re.compile(r"^\s*import\s+[\s\S]*?from\s+['\"][^'\"]*['\"];?\s*$", re.MULTILINE)
EXPORT_RE = re.compile(r"^export\s+", re.MULTILINE)

def main():
    parts = ["// AUTO-GENERATED by build.py -- do not edit directly, edit src/*.js and rerun.\n"]
    for name in ORDER:
        text = (SRC / name).read_text(encoding="utf-8")
        text = IMPORT_RE.sub("", text)
        text = EXPORT_RE.sub("", text)
        parts.append(f"\n// ---- {name} ----\n{text}")
    bundle = "\n".join(parts)
    (ROOT / "game.bundle.js").write_text(bundle, encoding="utf-8")
    print(f"wrote game.bundle.js ({len(bundle)} bytes)")

if __name__ == "__main__":
    main()
